#[ParameterName]
#array_index=1 #zero-based
#low=1
#high=2
#step=0.5
#optguess=1
#minbound=1
#maxbound=2

[SpecificLeafArea]
low=0.5
high=1.5

[MaxAssimilationRate]
low=25
high=35

[DaylengthRequirement]
low=17
high=23

[BaseDaylength]
low=5
high=9

[CropSpecificMaxRootingDepth]
low=0.8
high=2.0

[FieldConditionModifier]
low=0.5
high=1
