[project]
name = "monica-cz_clim4cast"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.10,<3.13"
authors = [{ name = "Michael Berg-Mohnicke", email = "michael.berg@zalf.de" }]
dependencies = [
    "tomli>=2.2.1,<3",
    "tomli-w>=1.2.0,<2",
    "zalfmas-common>=0.1.26,<0.2",
    "zalfmas-capnp-schemas>=0.1.33,<0.2",
    "zalfmas-fbp>=0.2.18,<0.3",
    "zalfmas-services>=0.1.7,<0.2",
    "numpy(>=2.1.2)",
    "pycapnp (>=2.1.0,<3.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
libsodium = ">=1.0.20,<2"
matplotlib = ">=3.10.5,<4"
pixi-pycharm = ">=0.0.8,<0.0.9"
spotpy = ">=1.6.2,<2"
ruff = ">=0.12.10,<0.13"
netcdf4 = ">=1.7.2,<2"
numpy = ">=2.2.6,<3"

[tool.pixi.pypi-options]
index-url = "https://test.pypi.org/simple"
extra-index-urls = ["https://pypi.org/simple"]
index-strategy = "unsafe-best-match"


# Referencing local packages in editable mode for pixi
# [tool.pixi.pypi-dependencies]
# zalfmas-common = { path = "../mas_python_common", editable = true }
# zalfmas-capnp-schemas = { path = "../mas_capnproto_schemas", editable = true }

# Referencing local packages in editable mode for poetry
# [tool.poetry.dependencies]
# zalfmas-common = { path = "../mas_python_common", develop = true }
# zalfmas-capnp-schemas = { path = "../mas_capnproto_schemas", develop = true }

[tool.poetry.group.dev.dependencies]
ruff = "^0.12.10"

